### ISSUE TITLE
Why not to use getCustomParamsString one more time?

### ISSUE THREAD

**Issue by rusjoan** [idma/robokassa#7]
Hi!

Really can't find the reason not to use getCustomParamsString() in line 102 of Payment.php
Maybe I wrong but such a lil refactoring would be good.

**Comment by jhaoda** [comment]
Потому что `getCustomParamsString()` проверяет элементы массива на валидность, ища префикс `shp_`. Делать эту работу над массивом, состоящим из заведомо валидных элементов, несколько бессмысленно.
Но я с удовольствием приму пуллреквест, который решит эту неувязку.

**Comment by rusjoan** [comment]
А, в этом дело... Тогда да, можно и так оставить, оптимальней же.
